FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
RUN apt-get update && apt-get install -y libcap2-bin libsnappy1v5 && \
    ln -s /lib/arm-linux-gnueabihf/libdl.so.2 /usr/lib/arm-linux-gnueabihf/libdl.so && \
    ln -s /lib/arm-linux-gnueabihf/libc.so.6 /usr/lib/arm-linux-gnueabihf/libc.so && \
	rm -rf /var/lib/apt/lists/*
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk AS build
RUN apt-get update && apt-get install -y libcap2-bin libsnappy1v5 && \
    ln -s /lib/arm-linux-gnueabihf/libdl.so.2 /usr/lib/arm-linux-gnueabihf/libdl.so && \
    ln -s /lib/arm-linux-gnueabihf/libc.so.6 /usr/lib/arm-linux-gnueabihf/libc.so && \
	rm -rf /var/lib/apt/lists/*

WORKDIR /src
COPY ["Hexastore.Web/Hexastore.Web.csproj", "Hexastore.Web/"]
RUN dotnet restore "Hexastore.Web/Hexastore.Web.csproj"
COPY . .
WORKDIR "/src/Hexastore.Web"
RUN dotnet build "Hexastore.Web.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Hexastore.Web.csproj" -c Release -o /app

FROM base AS final
RUN apt-get update && apt-get install -y libcap2-bin libsnappy1v5 && \
    ln -s /lib/arm-linux-gnueabihf/libdl.so.2 /usr/lib/arm-linux-gnueabihf/libdl.so && \
    ln -s /lib/arm-linux-gnueabihf/libc.so.6 /usr/lib/arm-linux-gnueabihf/libc.so && \
	rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=publish /app .

ENV LD_DEBUG=/app/bin/Debug/netcoreapp2.2/native/amd64:/app/bin/Release/netcoreapp2.2/native/amd64

ENTRYPOINT ["dotnet", "Hexastore.Web.dll"]